#!/bin/bash

#
#-----------------------------------------------------------------------
#
# This script copies files from various directories into the experiment
# directory, creates links to some of them, and modifies others (e.g. 
# templates) to customize them for the current experiment setup.
#
#-----------------------------------------------------------------------
#

#
#-----------------------------------------------------------------------
#
# Source the variable definitions file and the bash utility functions.
#
#-----------------------------------------------------------------------
#
. ${GLOBAL_VAR_DEFNS_FP}
. $USHDIR/source_util_funcs.sh
#
#-----------------------------------------------------------------------
#
# Save current shell options (in a global array).  Then set new options
# for this script/function.
#
#-----------------------------------------------------------------------
#
{ save_shell_opts; set -u +x; } > /dev/null 2>&1
set -xu #cltthink
#
#-----------------------------------------------------------------------
#
# Get the full path to the file in which this script/function is located 
# (scrfunc_fp), the name of that file (scrfunc_fn), and the directory in
# which the file is located (scrfunc_dir).
#
#-----------------------------------------------------------------------
#
scrfunc_fp=$( readlink -f "${BASH_SOURCE[0]}" )
scrfunc_fn=$( basename "${scrfunc_fp}" )
scrfunc_dir=$( dirname "${scrfunc_fp}" )
#
#-----------------------------------------------------------------------
#
# Print message indicating entry into script.
#
#-----------------------------------------------------------------------
#
print_info_msg "
========================================================================
Entering script:  \"${scrfunc_fn}\"
In directory:     \"${scrfunc_dir}\"

This is the J-job script for the task that runs a forecast with FV3 for 
the specified cycle.
========================================================================"
#
#-----------------------------------------------------------------------
#
# Create the INPUT and RESTART directories under the cycle directory.
#
#-----------------------------------------------------------------------
#
if [ $tmmark = tm12 ] ; then
     export tmmark_next=tm06
else
    nexthr=$(( `echo $tmmark | cut -c 3-4` - 1 ))
     [ $nexthr -lt 0 ] &&  nexthr=0
    tmmark_next=tm$(printf "%02d" $nexthr)
fi

export PDY=`echo $CDATE | cut -c 1-8`
export CYC=`echo $CDATE | cut -c 9-10`

export COMOUT=${COMROOT}/${envir}/${RUN}.${PDY}/${CYC}
export GUESSdir=$COMOUT/guess.${tmmark_next}
mkdir_vrfy -p $GUESSdir 
export DATA=${DATA:-$CYCLE_DIR/$CDATE/${job}_${CYC}}
mkdir_vrfy -p $DATA
mkdir_vrfy -p ${DATA}/INPUT
mkdir_vrfy -p ${DATA}/RESTART

#-------------------------set up some parameters ----------------

# get valid time of forecast
offset_fcst=`echo $tmmark_next | cut -c 3-4`
offset_init=`echo $tmmark | cut -c 3-4`

export CYCLEfcst=`$NDATE -${offset_fcst} $CDATE`
export PDYfcst=`echo $CYCLEfcst | cut -c 1-8`
export CYCfcst=`echo $CYCLEfcst | cut -c 9-10`

export CYCLEinit=`$NDATE -${offset_init} $CDATE`

export GUESSdir=$COMOUT/guess.${tmmark_next}
mkdir -p $GUESSdir
export ANLdir=$COMOUT/anl.${tmmark_next}
mkdir -p $ANLdir
#
#-----------------------------------------------------------------------
#
# Call the ex-script for this J-job and pass to it the necessary varia-
# bles.
#
#-----------------------------------------------------------------------
#
$SCRIPTSDIR/dev-exregional_run_fcst.sh \
  CYCLE_DIR="${CYCLE_DIR}" || \
print_err_msg_exit "\
Call to ex-script corresponding to J-job \"${scrfunc_fn}\" failed."
#
#-----------------------------------------------------------------------
#
# Print exit message.
#
#-----------------------------------------------------------------------
#
print_info_msg "
========================================================================
Exiting script:  \"${scrfunc_fn}\"
In directory:    \"${scrfunc_dir}\"
========================================================================"
#
#-----------------------------------------------------------------------
#
# Restore the shell options saved at the beginning of this script/func-
# tion.
#
#-----------------------------------------------------------------------
#
{ restore_shell_opts; } > /dev/null 2>&1

